version: "3.8"

services:
  mshauri:
    build: .
    container_name: mshauri
    volumes:
      - ./:/mshauri
    env_file:
      - .env
    ports:
      - "81:8000"
    depends_on:
      - mshauri-db

  mshauri-db:
    image: postgres:latest
    container_name: mshauri-db
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

  admin:
    image: adminer
    container_name: admin
    restart: always
    depends_on:
      - mshauri-db
    ports:
      - "8080:8080"
