"""initial migration

Revision ID: f77e259be82f
Revises: 
Create Date: 2024-08-08 15:46:46.711992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77e259be82f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cme',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drill',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentors_checklist',
    sa.Column('cme_completion_date', sa.Date(), nullable=False),
    sa.Column('cme_unique_id', sa.BigInteger(), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('date_submitted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drill_unique_id', sa.Integer(), nullable=False),
    sa.Column('essential_cme_topic', sa.Boolean(), nullable=False),
    sa.Column('essential_drill_topic', sa.Boolean(), nullable=False),
    sa.Column('facility_code', sa.String(length=100), nullable=False),
    sa.Column('facility_name', sa.String(length=100), nullable=False),
    sa.Column('id_number_cme', sa.String(length=100), nullable=True),
    sa.Column('id_number_drill', sa.String(length=100), nullable=True),
    sa.Column('mentor_name', sa.String(length=100), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('success_story', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cme_unique_id'], ['cme.id'], ),
    sa.ForeignKeyConstraint(['drill_unique_id'], ['drill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentors_checklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentors_checklist_cme_unique_id'), ['cme_unique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentors_checklist_drill_unique_id'), ['drill_unique_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors_checklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentors_checklist_drill_unique_id'))
        batch_op.drop_index(batch_op.f('ix_mentors_checklist_cme_unique_id'))

    op.drop_table('mentors_checklist')
    op.drop_table('drill')
    op.drop_table('cme')
    # ### end Alembic commands ###
